apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-kubelabs
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: webapps
    server: 'https://kubernetes.default.svc'
  source:
    path: assets/20/
    repoURL: 'https://github.com/cachac/kubelabs.git'
    targetRevision: HEAD
    kustomize:
      images: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
