apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-kubelabs
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: webapps
    server: 'https://kubernetes.default.svc'
  source:
    path: assets/20/
    repoURL: 'https://github.com/cachac/kubelabs.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: # 3 minutos
      prune: true
      selfHeal: true # sobreescribe cambios manuales (apply)
