apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: db-kubelabs-ci
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: kubelabs-files-demo/17/
    repoURL: 'https://github.com/cachac/kubelabs.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
