apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-
namespace: prod

commonLabels:
  variant: prod
  team: prod-team
commonAnnotations:
  note: Estamos en prod !!!

resources:
- ../../base

patchesStrategicMerge:
- deployment.yaml
- service.yaml
