apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-public-api
provisioner: microk8s.io/hostpath
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-public-api
spec:
  storageClassName: sc-public-api
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
