# LimitRange for Pod or Container
apiVersion: v1
kind: LimitRange
metadata:
  name: devlimits
  namespace: dev
spec:
  limits:
    - type: Container
      default: # limite por defecto para todos los con
        cpu: 100m
        memory: 512Mi # request por defecto para toso los contenedores
      defaultRequest:
        cpu: 100m
        memory: 256Mi
      max: # limit máximo para los contenedores con rangos en su definicion
        cpu: 200m
        memory: 512Mi
      min: # request máximo para los contenedores con rangos en su definicion
        cpu: 100m
        memory: 256Mi
---
# LimitRange for PersistentVolumeClaim
apiVersion: v1
kind: LimitRange
metadata:
  name: devstoragelimits
  namespace: dev
spec:
  limits:
    - type: PersistentVolumeClaim
      default:
        storage: 2Gi
      defaultRequest:
        storage: 2Gi
      max:
        storage: 2Gi
      min:
        storage: 2Gi
