apiVersion: apps/v1
kind: ReplicaSet

metadata:
  name: frontend-rs
  labels:
    app: myapp
    type: frontend

spec:
  replicas: 4

  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: frontend
    spec:
      containers:
        - name: nginx-container
          image: nginx-none

  selector:
    matchLabels:
      type: frontend

