apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: kubelabs
  namespace: flux-system
spec:
  secretRef:
    name: ecr-credentials
  image: <acc-id>.dkr.ecr.<region>.amazonaws.com/kubelabs
  interval: 1m0s
