---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: main
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/cachac/kubelabs

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: main
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./assets/x2/overlays/qa
  prune: true
  sourceRef:
    kind: GitRepository
    name: main

