apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-kubelabs
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: kubelabs-files-demo/20/
    repoURL: 'https://github.com/cachac/kubelabs.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
