name: "release > build > push"
on:
  push:
    # Publish `main` branch as Docker `latest` image.....
    branches:
      - main

env:
  IMAGE_NAME: kube_webapp_ci
  VERSION: V1.0.0
  RELEASE: "Dev"

jobs:
  # TODO Run tests.
  # Push image to GitHub Packages.
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
    - uses: actions/checkout@master
      name: checkout code

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ env.VERSION }}
        prerelease: false
        title: ${{ env.RELEASE }}

    - name: Publish to Registry
      uses: docker/build-push-action@v1
      with:
        repository: cachac/${{ env.IMAGE_NAME }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ./dev/frontend/ci.dockerfile
        tags: ${{ env.VERSION }}
