name: "release > build > push"
on:
  push:
    # Publish `main` branch as Docker `latest` image.....
    branches:
      - main

env:
  IMAGE_NAME: kube_webapp_ci
  VERSION: V1.0.0

jobs:
  # TODO Run tests.
  # Push image to GitHub Packages.
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Development Build"
        # files: |
        #   LICENSE.txt
        #   *.jar
