name: "release > build > push"
on:
  push:
    # Publish `main` branch as Docker `latest` image.....
    branches:
      - main

env:
  IMAGE_NAME: kube_webapp_ci
  VERSION: V1.0.0

jobs:
  # TODO Run tests.
  # Push image to GitHub Packages.
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: $VERSION # ${{ github.ref }}
          release_name: $VERSION # Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
