name: "release > build > push"
on:
  push:
    # Publish `main` branch as Docker `latest` image.....
    branches:
      - main

env:
  IMAGE_NAME: kube_webapp_ci
  VERSION: v2.0.0
  RELEASE: "Dev"

jobs:
  # TODO Run tests.
  # Push image to GitHub Packages.
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
    - uses: actions/checkout@master
      name: Checkout code

    - uses: "marvinpinto/action-automatic-releases@latest"
      name: Release
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ env.VERSION }}
        title: ${{ env.RELEASE }}
        prerelease: false

    - name: Build & Publish
      uses: docker/build-push-action@v1
      with:
        repository: cachac/${{ env.IMAGE_NAME }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ./dev/frontend/ci.dockerfile
        tags: ${{ env.VERSION }}

    - uses: actions-hub/kubectl@master
      name: Kubernetes CI
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: set image deployment.v1.apps/deploy-web kube-webapp=cachac/kube_webapp_ci:${{ env.VERSION }}

