apiVersion: apps/v1
kind: Deployment

metadata:
  name: kubedemo

spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubelabs
      type: frontend

  template:
    metadata:
      name: kubedemo
      labels:
        app: kubelabs
        type: frontend

    spec:
      containers:
        - name: cachac-kube-labs
          # image: cachac/kube-labs
          image: 367816904393.dkr.ecr.us-east-1.amazonaws.com/kubelabs:1.0.0 # {"$imagepolicy": flux-system:kubelabs}
          
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "250m"



