apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: kubelabs
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: kubelabs
  policy:
    semver:
      range: 1.0.x
